Pinball.onGate(Pinball.Gate.Gate1, function () {
    Pinball.ledColor(Pinball.Led.Led1, Color.Green)
    Pinball.playVideo(Pinball.Media.Video1)
    Pinball.ledColor(Pinball.Led.Led1, Color.Magenta)
    Pinball.showBackground()
})
Pinball.onGate(Pinball.Gate.Gate2, function () {
    Pinball.ledColor(Pinball.Led.Led2, Color.Green)
    Pinball.playVideo(Pinball.Media.Video2)
    Pinball.ledColor(Pinball.Led.Led2, Color.Yellow)
    Pinball.showBackground()
})
Pinball.setVideoFile("poort1.mp4", Pinball.Media.Video1)
Pinball.setVideoFile("poort2.mp4", Pinball.Media.Video2)
Pinball.setBackgrFile("achtergrond.jpg")
Pinball.showBackground()
Pinball.ledColor(Pinball.Led.Led1, Color.Magenta)
Pinball.ledColor(Pinball.Led.Led2, Color.Yellow)
basic.forever(function () {
    Pinball.ledColor(Pinball.Led.Led3, Color.Red)
    basic.pause(100)
    Pinball.ledColor(Pinball.Led.Led3, Color.Yellow)
    basic.pause(100)
    Pinball.ledColor(Pinball.Led.Led3, Color.Green)
    basic.pause(100)
    Pinball.ledColor(Pinball.Led.Led3, Color.Cyan)
    basic.pause(100)
    Pinball.ledColor(Pinball.Led.Led3, Color.Blue)
    basic.pause(100)
    Pinball.ledColor(Pinball.Led.Led3, Color.Magenta)
    basic.pause(100)
})
